name: Run Regional
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
        image: para2x/uiuc_custom_full_psims:3.0
        credentials:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        volumes:
            - ${{ github.workspace }}:/pysims/data
    steps:
      - name: 0-Force install git latest
        run: |
          apt-get install -y software-properties-common \
          && apt-get update \
          && add-apt-repository -y ppa:git-core/ppa \
          && apt-get update \
          && apt-get install -y git
          
      - name: 1-Checkout Checkout
        uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}
            
      - name: 2-Checkout the latest data inputs 
        uses: actions/checkout@main
        with:
          repository: FarmerAssist/ModelInputs
          path: Data
          
      - name: 3-Checkout the latest simulation
        uses: actions/checkout@v2
        with:
          repository: FarmerAssist/Simulation
          path: Sims
          
      - name: 4-Checkout the latest pSIMS
        uses: actions/checkout@v2
        with:
          repository: AgronomicForecastingLab/pysims
          token: ${{ secrets.GITHUBTOKEN }}
          path: pysims
     
      - name: 5-Run the model
        run: |
          . /pysims/data/Sims/Champaign/test_apsim_TL.sh   
          
      - name: 6.0-Cleaning dirs
        run: |
          rm -r /pysims/data/Data /pysims/data/Sims /pysims/data/pysims  

      - name: 6.1-Cleaning files nc
        run: |
          find /pysims/data -name "*.nc*" -type f -delete
      
      - name: 6.2-Cleaning files tar
        run: |
          find /pysims/data -name "*.tar*" -type f -delete 
          
      - name: 6.3-Cleaning files sims
        run: |
          find /pysims/data -name "*.sim" -type f -delete  
      
      - name: 6.4-Cleaning files sums
        run: |
          find /pysims/data -name "*.sum" -type f -delete  
      
      - name: 6.5-Cleaning files met
        run: |
          find /pysims/data -name "*.met" -type f -delete  
      
      - name: 6.6-Cleaning files old
        run: |
          find /pysims/data -name "*.old" -type f -delete            
          
      - name: 7-Commit the model outputs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "A new round of simulations"
          repository: /pysims/data/
      

      

